In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
from scraping import Dbase
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = Dbase()
df1 = data.imdb_requests()

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   titles         250 non-null    object
 1   genre1         250 non-null    object
 2   genre2         250 non-null    object
 3   genre3         250 non-null    object
 4   nb_genres      250 non-null    int64
 5   released_year  250 non-null    int64
 6   director1      250 non-null    object
 7   director2      250 non-null    object
 8   director3      250 non-null    object
 9   nb_directors   250 non-null    int64
 10  grade          250 non-null    float64
 11  votes          250 non-null    int64
 12  gross(M$)      250 non-null    float64
dtypes: float64(2), int64(4), object(7)
memory usage: 25.5+ KB

In [4]:
df1.head(16)

,titles,genre1,genre2,genre3,nb_genres,released_year,director1,director2,director3,nb_directors,grade,votes,gross(M$)
0,Les Évadés,Drama,Drama,Drama,1,1994,Frank Darabont,Frank Darabont,Frank Darabont,1,9.3,2384498,28.34
1,Le parrain,Crime,Drama,Drama,2,1972,Francis Ford Coppola,Francis Ford Coppola,Francis Ford Coppola,1,9.2,1652566,134.97
2,The Dark Knight : Le Chevalier noir,Action,Crime,Drama,3,2008,Christopher Nolan,Christopher Nolan,Christopher Nolan,1,9.0,2347962,534.86
3,"Le parrain, 2ème partie",Crime,Drama,Drama,2,1974,Francis Ford Coppola,Francis Ford Coppola,Francis Ford Coppola,1,9.0,1149888,57.30
4,12 Hommes en colère,Crime,Drama,Drama,2,1957,Sidney Lumet,Sidney Lumet,Sidney Lumet,1,9.0,704057,4.36
5,Le Seigneur des anneaux : Le Retour du roi,Action,Adventure,Drama,3,2003,Peter Jackson,Peter Jackson,Peter Jackson,1,8.9,1668051,377.85
6,Pulp Fiction,Crime,Drama,Drama,2,1994,Quentin Tarantino,Quentin Tarantino,Quentin Tarantino,1,8.9,1857194,107.93
7,La liste de Schindler,Biography,Drama,History,3,1993,Steven Spielberg,Steven Spielberg,Steven Spielberg,1,8.9,1232952,96.90
8,Inception,Action,Adventure,Sci-Fi,3,2010,Christopher Nolan,Christopher Nolan,Christopher Nolan,1,8.8,2106219,292.58
9,Fight Club,Drama,Drama,Drama,1,1999,David Fincher,David Fincher,David Fincher,1,8.8,1886437,37.03
10,Le Seigneur des anneaux : La Communauté de l'a...,Action,Adventure,Drama,3,2001,Peter Jackson,Peter Jackson,Peter Jackson,1,8.8,1688541,315.54
11,Forrest Gump,Drama,Romance,Romance,2,1994,Robert Zemeckis,Robert Zemeckis,Robert Zemeckis,1,8.8,1844811,330.25
12,"Le Bon, la brute, le truand",Western,Western,Western,1,1966,Sergio Leone,Sergio Leone,Sergio Leone,1,8.8,698626,6.10
13,Le Seigneur des anneaux : Les Deux Tours,Action,Adventure,Drama,3,2002,Peter Jackson,Peter Jackson,Peter Jackson,1,8.7,1508418,342.55
14,Matrix,Action,Sci-Fi,Sci-Fi,2,1999,Lana Wachowski,Lilly Wachowski,Lilly Wachowski,2,8.7,1705257,171.48
15,Les affranchis,Biography,Crime,Drama,3,1990,Martin Scorsese,Martin Scorsese,Martin Scorsese,1,8.7,1039505,46.84